spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-old-cake-a1cfjvli-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RXoavK17IDlP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

spring.web.resources.static-locations=classpath:/static/,file:./uploads/